filebeat.inputs:
  - type: filestream
    id: app-logs
    paths:
      - /usr/local/var/log/*.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
    # Optimize for low latency
    scan_frequency: 1s
    harvester_buffer_size: 16384

processors:
  - add_host_metadata: {}
  - add_docker_metadata: {}

output.logstash:
  hosts: ["logstash:5044"]
  # Flush events more frequently for lower latency
  flush_interval: 1s
  bulk_max_size: 50